### ISSUE TITLE
Building and installing estnltk 1.6

### ISSUE THREAD

**Issue by kristiank** [estnltk/estnltk#102]
After building EstNLTK 1.6 I get the following error when importing the package

```python3
>>> import estnltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/__init__.py", line 2, in <module>
    from estnltk.logger import logger
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/logger.py", line 2, in <module>
    import tqdm
ImportError: No module named 'tqdm'
```

Maybe the package is not marked as a dependency for the installation script?

**Comment by paultammo** [comment]
Yes, currently
`pandas IPython networkx lxml requests regex matplotlib sqlalchemy nltk tqdm psycopg2 jupyter pytest`
may need manual installation.

**Comment by kristiank** [comment]
After having (two times from scratch) been able to run `python setup.py build` followed by `python setup.py install` I still end up with the following `ImportError` when I run python 3.5.6 from the root of the Git repository (not the `build` folder):

```python3
>>> import estnltk
Traceback (most recent call last):
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/vabamorf/vabamorf.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/kristian/miniconda3/envs/flesch/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'estnltk.vabamorf._vabamorf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/__init__.py", line 9, in <module>
    from estnltk.text import Text
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/text.py", line 515, in <module>
    from .resolve_layer_dag import DEFAULT_RESOLVER
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/resolve_layer_dag.py", line 71, in <module>
    from .taggers.text_segmentation.tokens_tagger import TokensTagger
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/taggers/__init__.py", line 21, in <module>
    from estnltk.taggers.morph_analysis.postanalysis_tagger import PostMorphAnalysisTagger
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/taggers/morph_analysis/postanalysis_tagger.py", line 16, in <module>
    from estnltk.taggers.morph_analysis.morf_common import IGNORE_ATTR
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/taggers/morph_analysis/morf_common.py", line 13, in <module>
    from estnltk.vabamorf.morf import get_group_tokens
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/vabamorf/__init__.py", line 4, in <module>
    from . import vabamorf as vm
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/vabamorf/vabamorf.py", line 17, in <module>
    _vabamorf = swig_import_helper()
  File "/home/kristian/Projektid/EstNLTK/github/estnltk/estnltk/vabamorf/vabamorf.py", line 16, in swig_import_helper
    return importlib.import_module('_vabamorf')
  File "/home/kristian/miniconda3/envs/flesch/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_vabamorf'
```

And when doing the import when having started python from the `build` folder I get a segmentation fault:
```python3
>>> import estnltk
Segmentation fault
```

Is `python setup.py build` and `python setup.py install` the correct way to build and install EstNLTK 1.6?

**Comment by soras** [comment]
I also get `ImportError: No module named '_vabamorf'` if I try to import estnltk in the root folder of estnltk's repository, but outside the root folder importing should be fine. 

*) If you have installed estnltk several times, try to completely remove the old version (`pip uninstall estnltk`) and then install it once again. For that, running `python setup.py install` should be enough;

*) If you use Ubuntu 18.04, there is [a discussion](https://github.com/estnltk/estnltk/issues/97) about the `Segmentation fault` encountered on that version and possible solutions. Unfortunately, I don't have experience with the new Ubuntu version, so I can't give further advice at the moment;

**Comment by paultammo** [comment]
It is a known low level interface error between C++ library and Python. Unofficial fix has been described in the [discussion](https://github.com/estnltk/estnltk/issues/97). We will fix this issue in the next release after we have tested it on all three platforms.

**Comment by soras** [comment]
Segmentation fault was related to the issue https://github.com/estnltk/estnltk/issues/97 and should be resolved in the latest version of EstNLTK.
