### ISSUE TITLE
all_synsets() meetodi veateade 1.1 versiooniga

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#17]
Sain sellise veateate, kui kasutasin `all_synsets` meetodit:
```
$ python estnltk/examples/wordnet.py 
Traceback (most recent call last):
  File "estnltk/examples/wordnet.py", line 4, in <module>
    print (len(wn.all_synsets()))
  File "/home/timo/projects/estnltk/estnltk/wordnet/wn.py", line 290, in all_synsets
    synsets = _get_synsets(synset_offsets)
  File "/home/timo/projects/estnltk/estnltk/wordnet/wn.py", line 107, in _get_synsets
    raw_synset = parser.parse_synset(offset)
  File "/home/timo/projects/estnltk/estnltk/wordnet/eurown.py", line 1469, in parse_synset
    rulez[select]()
  File "/home/timo/projects/estnltk/estnltk/wordnet/eurown.py", line 1193, in _status
    self.synset.variants[-1].status = as_unicode(self.fieldValue)
  File "/home/timo/projects/estnltk/estnltk/core.py", line 45, in as_unicode
    raise ValueError('Can only convert types {0} and {1}'.format(six.text_type, six.binary_type))
```

Selgus, et `self.fieldValue` on ühel juhul `int` tyypi. Muutsin paari rida failides, et ilma errorita toimiks:

eurown.py, rida 1193
wn.py, rida 233

Aga uuri, mis seal tegelikult valesti on, sest  mu muutused on lihtsalt ajutine häkk, et erroreid, mitte saada.

**Comment by tpetmanson** [comment]
fixed
