### ISSUE TITLE
wn.synsets() kooleb regexi metakarakterite korral

### ISSUE THREAD

**Issue by rsirel** [estnltk/estnltk#26]
wn.synsets() viskab erinevaid erroreid, kui otsitavas sõnas on regexi metakaraktereid (plussmärk, püstkriips, sulud, jne):

``` python
>>> wn.synsets(")")
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    wn.synsets(")")
  File "C:\Python27\lib\site-packages\estnltk\wordnet\wn.py", line 245, in synsets
    synset_idxes = _get_synset_idxes(lemma,pos)
  File "C:\Python27\lib\site-packages\estnltk\wordnet\wn.py", line 223, in _get_synset_idxes
    line_prefix = re.compile(line_prefix_regexp)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: unbalanced parenthesis
```

``` python
>>> wn.synsets("|")
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    wn.synsets("|")
  File "C:\Python27\lib\site-packages\estnltk\wordnet\wn.py", line 245, in synsets
    synset_idxes = _get_synset_idxes(lemma,pos)
  File "C:\Python27\lib\site-packages\estnltk\wordnet\wn.py", line 231, in _get_synset_idxes
    res_indices = [int(x) for x in result.group(1).split(' ')]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by tpetmanson** [comment]
Tundub, et kusagil on re.escape puudu

**Comment by swenlaur** [comment]
Current wordnet implementation does not have this issue.
