### ISSUE TITLE
post-installation tests fail on Win7x64, java 1.8.0_60-b27

### ISSUE THREAD

**Issue by AleksTk** [estnltk/estnltk#28]
[py34] C:\Users\distorti>python -m estnltk.run_tests
# .........................................................................................................................................................
## ERROR: test_document_creation_date (estnltk.tests.test_timex.TimexTest)

Traceback (most recent call last):
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\tests\test_timex.py", line 43, in test_document_creation_date
    self.assertEqual(text.timexes[0]['value'], '1986-12-21')
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\cached_property.py", line 26, in **get**
    value = obj.**dict**[self.func.**name**] = self.func(obj)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 738, in timexes
    self.tag_timexes()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 730, in tag_timexes
    self.**timex_tagger = load_default_timex_tagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 68, in load_default_timex_tagger
    timextagger = TimexTagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\timex.py", line 18, in __init**
    JavaProcess.**init**(self, 'Ajavt.jar', ['-pyvabamorf', '-r', os.path.join(JAVARES_PATH, 'reeglid.xml')])
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\javaprocess.py", line 50, in **init**
    stderr=subprocess.PIPE)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 754, in **init**
    _cleanup()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 474, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 1147, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
# 
## ERROR: test_tag_separately (estnltk.tests.test_timex.TimexTest)

Traceback (most recent call last):
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\tests\test_timex.py", line 14, in test_tag_separately
    self.assertListEqual(text.timexes, self.timexes)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\cached_property.py", line 26, in **get**
    value = obj.**dict**[self.func.**name**] = self.func(obj)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 738, in timexes
    self.tag_timexes()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 730, in tag_timexes
    self.**timex_tagger = load_default_timex_tagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 68, in load_default_timex_tagger
    timextagger = TimexTagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\timex.py", line 18, in __init**
    JavaProcess.**init**(self, 'Ajavt.jar', ['-pyvabamorf', '-r', os.path.join(JAVARES_PATH, 'reeglid.xml')])
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\javaprocess.py", line 50, in **init**
    stderr=subprocess.PIPE)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 754, in **init**
    _cleanup()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 474, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 1147, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
# 
## ERROR: test_various_examples (estnltk.tests.test_timex.TimexTest)

Traceback (most recent call last):
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\tests\test_timex.py", line 90, in test_various_examples
    for timex in text.timexes:
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\cached_property.py", line 26, in **get**
    value = obj.**dict**[self.func.**name**] = self.func(obj)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 738, in timexes
    self.tag_timexes()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 730, in tag_timexes
    self.**timex_tagger = load_default_timex_tagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\text.py", line 68, in load_default_timex_tagger
    timextagger = TimexTagger()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\timex.py", line 18, in __init**
    JavaProcess.**init**(self, 'Ajavt.jar', ['-pyvabamorf', '-r', os.path.join(JAVARES_PATH, 'reeglid.xml')])
  File "C:\Users\distorti\Anaconda\envs\py34\lib\site-packages\estnltk\javaprocess.py", line 50, in **init**
    stderr=subprocess.PIPE)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 754, in **init**
    _cleanup()
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 474, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\distorti\Anaconda\envs\py34\lib\subprocess.py", line 1147, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid

---

Ran 157 tests in 107.299s

**Comment by tpetmanson** [comment]
Kas sellega tulevad ka vead?
python3 -m unittest estnltk.tests.test_timex

Või sellega:
python3 -c "import estnltk; print(estnltk.Text('tänane kuupäev').timex_values)"

**Comment by AleksTk** [comment]
python -m unittest estnltk.tests.test_timex
...
----------------------------------------------------------------------
Ran 3 tests in 2.012s

OK

[py34] C:\Users\distorti>python -c "import estnltk; print(estnltk.Text('tänane kuupäev').timex_values)"
['2015-09-18']

**Comment by tpetmanson** [comment]
Väga kummaline, need on täpselt need samad testid, mis esimese käsuga failivad. Samuti on huvitav, et ka see kuupäeva test töötab.

**Comment by AleksTk** [comment]
Hm, kas sellest on abi: http://stackoverflow.com/questions/31888326/popen-fails-with-winerror-6-the-handle-is-invalid-in-cleanup-sometimes

**Comment by soras** [comment]
Eriti huvitav oli see, et osalausestajaga mingeid probleeme polnud, kuigi protsessimisloogika oli analoogne ajaväljendite tuvastajale. Aga osalausestaja (ClauseSegmenter) tõmmati ka "python -m estnltk.run_tests" poolt alati esimesena käima, ja paistab, et pärast käimatõmbamist jäid mingid asjad ripakile...
Igatahes tuli mõte, et katsetaks ClauseSegmenter'i protsessi(de) sulgemist pärast testide jooksutamist ja üllatavalt kombel oligi sellest abi - Windows 10 (Python 3.4, 32bit) all enam neid vigu enam ei tekkinud.

Praegu kirjutasin kõik osalausestaja ja ajaväljendite tuvastaja testid ümber nii, et tagger'id luuakse alati Text klassi väliselt ning vastavad protsessid pannakse ka pärast teste kinni. Lahenduse puuduseks on ilmselt see, et ei saa testida, kui hästi toimib Text klassi sees tagger'ite automaatne loomine. Aga võib-olla leidub ka mingi parem lahendus, nt protsesse sulgevate destruktorite tekitamine Java-protsesse kasutavatele tagger'itele?
