### ISSUE TITLE
Unable to run the example code snippet from estnltk/pyvabamorf

### ISSUE THREAD

**Issue by priidukull** [estnltk/estnltk#54]
Estnltk OSX python3.4 installation. Tried to run:

> > > from pyvabamorf import analyze
> > > from pprint import pprint
> > > pprint(analyze('Tüünete öötööde allmaaraudteejaam'))

Got:

```
Traceback (most recent call last):
  File "/Users/priidukull/Projects/legal_research/run_vabamorf.py", line 3, in <module>
    from estnltk import analyze
  File "/Users/priidukull/Projects/legal_research/legal_research_env/lib/python3.4/site-packages/estnltk/__init__.py", line 4, in <module>
    from .vabamorf.morf import Vabamorf, analyze, spellcheck, fix_spelling, synthesize, disambiguate
  File "/Users/priidukull/Projects/legal_research/legal_research_env/lib/python3.4/site-packages/estnltk/vabamorf/__init__.py", line 4, in <module>
    from . import vabamorf as vm
ImportError: cannot import name 'vabamorf'
```

**Comment by tpetmanson** [comment]
This example code snippet is obsolete -- the analyze method should be imported from `estnltk` package:
```
from estnltk import analyze
```

For learning the library, it is recommended to follow the manuals

http://estnltk.github.io/estnltk/1.3/index.html
http://estnltk.github.io/estnltk/1.3/tutorials/text.html

It might be also interesting to check out the NLP course materials that cover some aspects of estnltk: https://courses.cs.ut.ee/2015/pynlp/fall

**Comment by tpetmanson** [comment]
TODO: remove or fix the obsolete example

**Comment by priidukull** [comment]
Installed estnltk to a fresh environment and then:

    (legal_research_env) priiduksmacbook:legal_research priidukull$ python
    Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from estnltk import analyze
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/priidukull/Projects/legal_research/legal_research_env/lib/python3.4/site-packages/estnltk/__init__.py", line 4, in <module>
        from .vabamorf.morf import Vabamorf, analyze, spellcheck, fix_spelling, synthesize, disambiguate
      File "/Users/priidukull/Projects/legal_research/legal_research_env/lib/python3.4/site-packages/estnltk/vabamorf/__init__.py", line 4, in <module>
        from . import vabamorf as vm
    ImportError: cannot import name 'vabamorf'
    >>>

**Comment by priidukull** [comment]
Appearently the file estnltk/vabamorf/vabamorf.py was missing from my site--packages. Adding the file manually solved the issue for me.

**Comment by urdvr** [comment]
Appearently the file estnltk/vabamorf/vabamorf.py was missing from my site-packages. Adding the file manually solved the issue for me.

Probably connected with issue #47 .
